const materialID = {gas:0, liquid:1, solid:2};
const materialTransparent = [true, true, false];

function defaultPalette() {
  return [
    {name:"air", symbol:"A", material:"gas", colour:"#ddddff"},
  	{name:"water", symbol:"B", material:"liquid", colour:"#59c9ff"},
  	{name:"block #1", symbol:"C", material:"solid", colour:"#ffff00"},
  	{name:"block #2", symbol:"D", material:"solid", colour:"#ff0000"},

  	{name:"block #3", symbol:"E", material:"solid", colour:"#00ff00"},
  	{name:"block #4", symbol:"F", material:"solid", colour:"#0000ff"},
  	{name:"block #5", symbol:"G", material:"solid", colour:"#000000"},
  	{name:"block #6", symbol:"H", material:"solid", colour:"#ffffff"}//,
	//{name:"block #7", symbol:"I", material:"solid", colour:"#ff00ff"},
	//{name:"block #8", symbol:"J", material:"solid", colour:"#00ffff"}
  ]
}

function creativePalette() {
	return[
		{name:"air", 		symbol:"A",		colour:"#ffffff", material:"gas"},
		{name:"stone", 		symbol:"B", 	colour:"#7f7f7f", material:"solid"},
		{name:"grass", 		symbol:"C", 	colour:"#9ccb6c", material:"solid"},
		{name:"dirt", 		symbol:"D", 	colour:"#79553a", material:"solid"},
		{name:"cobble", 	symbol:"E", 	colour:"#7f7f7f", material:"solid"},
		{name:"planks", 	symbol:"F", 	colour:"#ffffd1", material:"solid"},
		{name:"sapling", 	symbol:"G", 	colour:"#46cf2d", material:"solid"},
		{name:"bedrock", 	symbol:"H", 	colour:"#373737", material:"solid"},
		{name:"water", 		symbol:"I", 	colour:"#59c9ff", material:"liquid"},
		{name:"stillWater", symbol:"J", 	colour:"#59c9ff", material:"liquid"},
		{name:"lava", 		symbol:"K", 	colour:"#ff3700", material:"liquid"},
		{name:"stillLava", 	symbol:"L", 	colour:"#ff3700", material:"liquid"},
		{name:"sand", 		symbol:"M", 	colour:"#ffffd1", material:"solid"},
		{name:"gravel", 	symbol:"N", 	colour:"#a5a1a1", material:"solid"},
		{name:"goldOre", 	symbol:"O", 	colour:"#fcee4b", material:"solid"},
		{name:"ironOre", 	symbol:"P", 	colour:"#eeeeee", material:"solid"},
		{name:"coalOre", 	symbol:"Q", 	colour:"#373737", material:"solid"},
		{name:"treeTrunk", 	symbol:"R", 	colour:"#79553a", material:"solid"},
		{name:"leaves", 	symbol:"S", 	colour:"#46cf2d", material:"liquid"},
		{name:"sponge", 	symbol:"T", 	colour:"#fcee4b", material:"solid"},
		{name:"glass", 		symbol:"U", 	colour:"#ffffff", material:"liquid"},
		{name:"red wool", 	symbol:"V", 	colour:"#ff0000", material:"solid"},
		{name:"orange wool",symbol:"W", 	colour:"#ffcc00", material:"solid"},
		{name:"yellow wool",symbol:"X", 	colour:"#ffff00", material:"solid"},
		{name:"lime wool", 	symbol:"Y", 	colour:"#eeffee", material:"solid"},
		{name:"green wool", symbol:"Z", 	colour:"#00ff00", material:"solid"},
		{name:"aqua wool", 	symbol:"Aa", 	colour:"#00ffcc", material:"solid"},
		{name:"cyan wool", 	symbol:"Ab", 	colour:"#00ccff", material:"solid"},
		{name:"blue wool", 	symbol:"Ac", 	colour:"#0000ff", material:"solid"},
		{name:"purple wool",symbol:"Ad", 	colour:"#cc00ff", material:"solid"},
		{name:"indigo wool",symbol:"Ae", 	colour:"#cc00cc", material:"solid"},
		{name:"violet wool",symbol:"Af", 	colour:"#ff00cc", material:"solid"},
		{name:"magenta wool",symbol:"Ag", 	colour:"#ff00ff", material:"solid"},
		{name:"pink wool", 	symbol:"Ah", 	colour:"#ffccff", material:"solid"},
		{name:"black wool", symbol:"Ai", 	colour:"#111111", material:"solid"},
		{name:"grey wool", 	symbol:"Aj", 	colour:"#aaaaaa", material:"solid"},
		{name:"white wool", symbol:"Ak", 	colour:"#ffffff", material:"solid"},
		{name:"daisy", 		symbol:"Al", 	colour:"#ffff00", material:"solid"},
		{name:"rose", 		symbol:"Am", 	colour:"#ff0000", material:"solid"},
		{name:"brownMush", 	symbol:"An", 	colour:"#aa9988", material:"solid"},
		{name:"redMush", 	symbol:"Ao", 	colour:"#aa0000", material:"solid"},
		{name:"goldsolid", 	symbol:"Ap", 	colour:"#fcee4b", material:"solid"},
		{name:"ironsolid", 	symbol:"Aq", 	colour:"#dddddd", material:"solid"},
		{name:"twoSlab", 	symbol:"Ar", 	colour:"#7f7f7f", material:"solid"},
		{name:"slab", 		symbol:"As", 	colour:"#7f7f7f", material:"solid"},
		{name:"brick", 		symbol:"At", 	colour:"#aa9988", material:"solid"},
		{name:"bomb", 		symbol:"Au", 	colour:"#ff0000", material:"solid"},
		{name:"bookshelf", 	symbol:"Av", 	colour:"#ffffd1", material:"solid"},
		{name:"mossStone", 	symbol:"Aw", 	colour:"#224422", material:"solid"},
		{name:"obsidian", 	symbol:"Ax", 	colour:"#000000", material:"solid"},
		{name:"cobbleSlab", symbol:"Ay", 	colour:"#000000", material:"solid"},
		{name:"rope", 		symbol:"Az", 	colour:"#000000", material:"solid"},
		{name:"sandStone", 	symbol:"Ba", 	colour:"#000000", material:"solid"},
		{name:"snow", 		symbol:"Bb", 	colour:"#000000", material:"solid"},
		{name:"fire", 		symbol:"Bc", 	colour:"#000000", material:"solid"},
		{name:"lPink", 		symbol:"Bd", 	colour:"#000000", material:"solid"},
		{name:"fGreen", 	symbol:"Be", 	colour:"#000000", material:"solid"},
		{name:"brown", 		symbol:"Bf", 	colour:"#000000", material:"solid"},
		{name:"dblue", 		symbol:"Bg", 	colour:"#000000", material:"solid"},
		{name:"turq", 		symbol:"Bh", 	colour:"#000000", material:"solid"},
		{name:"ice", 		symbol:"Bi", 	colour:"#000000", material:"liquid"},
		{name:"ceramic", 	symbol:"Bj", 	colour:"#000000", material:"solid"},
		{name:"magma", 		symbol:"Bk", 	colour:"#000000", material:"solid"},
		{name:"pillar", 	symbol:"Bl", 	colour:"#000000", material:"solid"},
		{name:"crate", 		symbol:"Bm", 	colour:"#000000", material:"solid"},
		{name:"stoneBrick", symbol:"Bn", 	colour:"#bbbbbb", material:"solid"}

	]
}
